### ISSUE TITLE
Add kernel-irqchip parameter for WHPX

### ISSUE THREAD

**Issue by levelad** [Tech-FZ/EmuGUI-PreRelease#47]
Please add a kernel-irqchip checkbox for the WHPX accelerator as mentioned here:

https://gitlab.com/qemu-project/qemu/-/issues/346

`-accel whpx,kernel-irqchip=off`

It will fix this error:

`whpx: injection failed, MSI (0, 0) delivery: 0, dest_mode: 0, trigger mode: 0, vector: 0, lost (c0350005)`

**Comment by Tech-FZ** [comment]
If I get to test it on another PC, sure, because my own PC doesn't support WHPX at all. I'm looking forward to replace it tho as it has caused some trouble lately.

**Comment by levelad** [comment]
Do you mean your hardware does not support AMD-V/Intel VT-x or your OS is too old (no Windows Hypervisor-Plattform), e.g. Windows 7?

**Comment by Tech-FZ** [comment]
The PC originally came with Windows 7, yes.

**Comment by Tech-FZ** [comment]
The next pre-release will contain this potential fix.

**Comment by Tech-FZ** [comment]
The next pre-release will contain this potential fix.

**Comment by Tech-FZ** [comment]
I did add it already, so I'll close this issue.
