### ISSUE TITLE
Documents Folder on Windows is hardcoded

### ISSUE THREAD

**Issue by dynamyc010** [Tech-FZ/EmuGUI-PreRelease#61]
Hi,

I downloaded and ran the application, and while the "stable" build didn't even run, the pre-release build 2.1.0.5701_dev does actually run... but creates a Documents directory in the default location, instead of using the Documents folder I set up in Windows.

![newly made (left), actual documents (right)](https://github.com/user-attachments/assets/3b0182d3-9109-4db5-9f56-8658706d1a10)

![Python shell getting the documents dir](https://github.com/user-attachments/assets/99acc85e-1b3f-43ac-b18c-31e01adc7616)
win32com seems to get the right folder, so this doesn't seem to horribly hard to change.

Thanks,
dynamyc

**Comment by Tech-FZ** [comment]
Thanks for the info. I will check the code and update you on this situation.

**Comment by Tech-FZ** [comment]
I tried to reproduce your situation on a VM. Maybe you made a mistake while configuring your system. I followed https://superuser.com/a/1265778 and didn't have that issue. I recommend you make a full backup of your files, as well as a system restore point before changing these settings. Otherwise, you may risk losing your files.

The guide is originally made for Windows 10, which I used Version 22H2 of to test this. However, I'd assume that procedures won't be that different in case you want to switch to Windows 11 anyway.

**Comment by Tech-FZ** [comment]
![image](https://github.com/user-attachments/assets/bf2fa6cd-2bd8-4ec6-9d1a-05aad66e2195)

Here is an image to show you my result.

**Comment by dynamyc010** [comment]
I used the Windows UI way to change the location (this image is from an another machine; I don't have access to that PC right now)

![image](https://github.com/user-attachments/assets/2e213821-c8d6-41d3-85ba-3efca5e72890)

Every other application respected this setting, so I'm rather lost as well.
I'll do some more testing when I get home, try it again. I'll also check out the registry itself to see if its pointing to the right place.

**Comment by dynamyc010** [comment]
> I followed https://superuser.com/a/1265778 and didn't have that issue. 

I see what the difference is here; the actual User directory is unchanged for me, I merely just moved the folders inside there in the normal, Windows-supplied way. I still have the normal path (`C:\Users\dynamyc`) folder, which is where my AppData and other stuff puke their folders.

![image](https://github.com/user-attachments/assets/f9d416cb-9ad2-4286-a042-22c517a9811f)

**Comment by Tech-FZ** [comment]
I will see what I can do.

**Comment by Tech-FZ** [comment]
I have managed to reproduce your issue on a Windows 10 VM. I will attempt to apply your suggested fix in another pre-release build and notify you when you can test the changes.

**Comment by Tech-FZ** [comment]
I have released https://github.com/Tech-FZ/EmuGUI-PreRelease/releases/tag/v2.1.0.57aa_dev-winff for you to test it out. If it does not work, please tell me. If it works, please close this issue.

**Comment by dynamyc010** [comment]
hi, yes! it now properly determines the folder.
thank you! <3
