### ISSUE TITLE
New Discord server

### ISSUE THREAD

**Issue by Tech-FZ** [Tech-FZ/EmuGUI-PreRelease#7]
We just need to advertise on Readme and the application: https://discord.gg/rTGpYCwF89

**Comment by Tech-FZ** [comment]
It's on the readme now.

**Comment by the-amazing-atharva** [comment]
Hi!!

I would like to work on the README to make it more visually appealing by making some subtle syntax changes
Could you assign me the issue?

**Comment by Tech-FZ** [comment]
Okay then, I'll assign you.

**Comment by the-amazing-atharva** [comment]
Thanks, working on it soon!

**Comment by Tech-FZ** [comment]
Everything is done here.
