### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by the-amazing-atharva** [Tech-FZ/EmuGUI-PreRelease#9]
Hey,

I was thinking I could add a general code of conduct file to the project 
Thoughts?

**Comment by Tech-FZ** [comment]
Yeah, we should really work out a code of conduct now. It's necessary.

A few examples are
- [Ubuntu's Code of Conduct 2.0](https://ubuntu.com/community/governance/code-of-conduct)
- [The Code of Conduct from the Document Foundation](https://www.documentfoundation.org/code-of-conduct/)

**Comment by the-amazing-atharva** [comment]
Done!
Sending a PR

**Comment by Tech-FZ** [comment]
The Code of Conduct has been approved.
